/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package entorno;

import java.awt.BorderLayout;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.WindowConstants;
import javax.swing.table.TableModel;
import persistencia.ModeloListadoCentros;

/**
 *
 * @author Antonio Paniagua <antoniopaniagua@iescastelar.com>
 */
public class MainFrame extends javax.swing.JFrame {

    TableModel tableModel = new ModeloListadoCentros();
    JTable jTableListadoCentros;
    AddCentroPanel addCentroPanel = new AddCentroPanel();

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jPanelListadoCentros = new javax.swing.JScrollPane();
        javax.swing.JTable jTableListadoCentros = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCentros = new javax.swing.JMenu();
        menuCentrosInsertar = new javax.swing.JMenuItem();
        menuCentrosListado = new javax.swing.JMenuItem();
        menuCentrosBorrar = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuSalir = new javax.swing.JMenu();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTableListadoCentros.setModel(tableModel);
        jPanelListadoCentros.setViewportView(jTableListadoCentros);

        menuCentros.setText("Centros");

        menuCentrosInsertar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        menuCentrosInsertar.setText("Añadir Nuevo Centro");
        menuCentrosInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCentrosInsertarActionPerformed(evt);
            }
        });
        menuCentros.add(menuCentrosInsertar);

        menuCentrosListado.setText("Listado de Centros");
        menuCentrosListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCentrosListadoActionPerformed(evt);
            }
        });
        menuCentros.add(menuCentrosListado);

        menuCentrosBorrar.setText("Borrar Centro");
        menuCentrosBorrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCentrosBorrarMouseClicked(evt);
            }
        });
        menuCentrosBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCentrosBorrarActionPerformed(evt);
            }
        });
        menuCentros.add(menuCentrosBorrar);

        jMenuItem1.setText("Borrar Centro en Condiciones");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuCentros.add(jMenuItem1);

        jMenuBar1.add(menuCentros);

        menuSalir.setText("Salir");
        menuSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSalirMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelListadoCentros, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelListadoCentros, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCentrosBorrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCentrosBorrarMouseClicked
    }//GEN-LAST:event_menuCentrosBorrarMouseClicked

    private void menuCentrosBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCentrosBorrarActionPerformed
        BorrarFrame ventanaBorrar = new BorrarFrame();
        ventanaBorrar.setVisible(true);
    }//GEN-LAST:event_menuCentrosBorrarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        BorrarFrame2 ventanaBorrar = new BorrarFrame2();
        ventanaBorrar.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menuSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSalirMouseClicked
        int dialogButton = JOptionPane.YES_NO_OPTION;
        JOptionPane.showConfirmDialog(null, "¿Está seguro de que quiere salir de la aplicación?", "Atención", dialogButton);

        if (dialogButton == JOptionPane.YES_OPTION) {
            System.exit(NORMAL);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_menuSalirMouseClicked

    private void menuCentrosListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCentrosListadoActionPerformed
        addCentroPanel.setVisible(false);
        this.remove(addCentroPanel);
        this.add(jPanelListadoCentros);
        jPanelListadoCentros.setVisible(true);
        JTable jTableListadoCentros = new JTable(tableModel);
    }//GEN-LAST:event_menuCentrosListadoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jPanelListadoCentros.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void menuCentrosInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCentrosInsertarActionPerformed
        jPanelListadoCentros.setVisible(false);
        this.remove(jPanelListadoCentros);
        this.add(addCentroPanel, BorderLayout.CENTER);
        addCentroPanel.setVisible(true);

        //clonamos el layout que inserta netbeans, dado que su propia distribución de la escena
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(addCentroPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(addCentroPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        this.pack();
    }//GEN-LAST:event_menuCentrosInsertarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jPanelListadoCentros;
    private javax.swing.JMenu menuCentros;
    private javax.swing.JMenuItem menuCentrosBorrar;
    private javax.swing.JMenuItem menuCentrosInsertar;
    private javax.swing.JMenuItem menuCentrosListado;
    private javax.swing.JMenu menuSalir;
    // End of variables declaration//GEN-END:variables
}
